# Generated by Django 5.0.3 on 2025-12-07 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogcomment_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-pub_time'], 'verbose_name': '博客', 'verbose_name_plural': '博客'},
        ),
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ['-pub_time'], 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
    ]
