# Generated by Django 5.0.3 on 2025-12-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_options_alter_blogcomment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cover',
            field=models.ImageField(blank=True, default='blog_covers/default.jpg', null=True, upload_to='blog_covers/'),
        ),
    ]
