# Generated by Django 5.0.3 on 2025-11-24 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mauth', '0002_alter_captcah_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Captcah',
            new_name='Captcha',
        ),
    ]
