# Generated by Django 5.0.3 on 2025-11-29 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mauth', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女'), ('S', '保密')], default='S', max_length=1, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地区'),
        ),
    ]
